// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// diff_bins
NumericVector diff_bins(NumericVector x, NumericVector y, double len_x, double len_y, String difference);
RcppExport SEXP movhm_diff_bins(SEXP xSEXP, SEXP ySEXP, SEXP len_xSEXP, SEXP len_ySEXP, SEXP differenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type len_x(len_xSEXP);
    Rcpp::traits::input_parameter< double >::type len_y(len_ySEXP);
    Rcpp::traits::input_parameter< String >::type difference(differenceSEXP);
    __result = Rcpp::wrap(diff_bins(x, y, len_x, len_y, difference));
    return __result;
END_RCPP
}
// find_margins
NumericVector find_margins(List l, String x, String y, double bin_width);
RcppExport SEXP movhm_find_margins(SEXP lSEXP, SEXP xSEXP, SEXP ySEXP, SEXP bin_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type bin_width(bin_widthSEXP);
    __result = Rcpp::wrap(find_margins(l, x, y, bin_width));
    return __result;
END_RCPP
}
