# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
diff_bins <- function(x, y, len_x, len_y, difference) {
    .Call('movhm_diff_bins', PACKAGE = 'movhm', x, y, len_x, len_y, difference)
}

find_margins <- function(l, x, y, bin_width) {
    .Call('movhm_find_margins', PACKAGE = 'movhm', l, x, y, bin_width)
}

